dependencies:
  trim_galore : "/share/ClusterShare/software/contrib/gi/trim_galore/0.4.0/trim_galore"
  cutadapt : "/share/ClusterShare/software/contrib/fabbus/python/2.7.3/bin/cutadapt"
  sambamba : "/home/xiuque/bin/sambamba_v0.5.8"
  markDup : "/home/xiuque/bin/MarkDuplicates.jar"
  gatk : "/home/xiuque/bin/GenomeAnalysisTK.jar"
  star: "/share/ClusterScratch/xiuque/testsnakemake/STAR-STAR_2.4.2a/bin/Linux_x86_64/STAR"
  star_genome_dir: "/share/ClusterScratch/xiuque/testsnakemake/lib/genomedir/"

references:
  genomeFile : "/share/ClusterShare/biodata/contrib/gi/gatk-resource-bundle/2.8/b37/human_g1k_v37.fasta"
  referenceIndel : "/share/ClusterShare/biodata/contrib/gi/gatk-resource-bundle/2.8/b37/Mills_and_1000G_gold_standard.indels.b37.vcf"
  referenceSnp : "/share/ClusterShare/biodata/contrib/gi/gatk-resource-bundle/2.8/b37/dbsnp_138.b37.vcf"
  referenceIndelG1K : "/share/ClusterShare/biodata/contrib/gi/gatk-resource-bundle/2.8/b37/1000G_phase1.indels.b37.vcf"
  

samples:
  - H1975-parental-04-02-2014
  - H1975-parental-08-04-2014
  - H1975-parental-16-05-2014
  - H1975-parental-24-03-2014
  - H1975-R-Erlotinib-03-01-2014
  - H1975-R-Erlotinib-04-02-2014
  - H1975-R-Erlotinib-08-07-2014
  - H1975-R-Erlotinib-16-05-2014
  - H1975-R-Erlotinib-24-03-2014





